export type FoundationCatalogItem = {
  code: string;
  family: string;
  cefr: 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';
  title: string;
  objectiveVi: string;
  objectiveEn: string;
  patterns: string[];
  uses: string[];
  prerequisites: string[];
  rule: string;
  examples: Array<
    [
      type: 'AFFIRMATIVE' | 'NEGATIVE' | 'QUESTION' | 'CONTEXTUAL' | 'CONTRASTIVE',
      english: string,
      vietnamese: string,
    ]
  >;
  error: [incorrect: string, corrected: string, explanationVi: string];
  exercise: {
    contextVi: string;
    sourceVi: string;
    answers: string[];
    requirements: string[];
    vocabulary: [
      lemma: string,
      partOfSpeech: string,
      definitionVi: string,
      conceptHintVi: string,
      phraseHintVi: string,
    ];
  };
};

// Independently authored A1-A2 batch. It intentionally contains compact editorial
// inputs; the authoring script expands these into the immutable bundle contract.
export const foundationCatalog: FoundationCatalogItem[] = [
  {
    code: 'THERE_IS_ARE',
    family: 'EXISTENTIAL_THERE',
    cefr: 'A1',
    title: 'There is/there are để nói sự tồn tại',
    objectiveVi: 'Dùng there is và there are để nói một hoặc nhiều sự vật tồn tại ở một nơi.',
    objectiveEn: 'Use there is and there are to say that one or more things exist in a place.',
    patterns: ['there is + singular noun', 'there are + plural noun', 'is/are there + noun?'],
    uses: ['Introduce things in a place or situation.', 'Ask whether something exists.'],
    prerequisites: ['BE_PRESENT_AFFIRMATIVE'],
    rule: 'Use there is with a singular noun and there are with a plural noun.',
    examples: [
      ['AFFIRMATIVE', 'There is a café near my house.', 'Có một quán cà phê gần nhà tôi.'],
      ['AFFIRMATIVE', 'There are two books on the desk.', 'Có hai quyển sách trên bàn.'],
      ['QUESTION', 'Is there a bank nearby?', 'Có ngân hàng nào gần đây không?'],
    ],
    error: [
      'There are a park here.',
      'There is a park here.',
      'Danh từ số ít a park đi với there is.',
    ],
    exercise: {
      contextVi: 'Bạn mô tả phòng khách cho một người bạn.',
      sourceVi: 'Có hai chiếc ghế cạnh cửa sổ.',
      answers: ['There are two chairs next to the window.', 'There are two chairs by the window.'],
      requirements: ['Use there are with a plural noun.', 'Preserve the quantity two.'],
      vocabulary: [
        'chair',
        'noun',
        'cái ghế',
        'Đồ vật dùng để ngồi.',
        'next to the window — cạnh cửa sổ',
      ],
    },
  },
  {
    code: 'HAVE_GOT_POSSESSION',
    family: 'POSSESSION',
    cefr: 'A1',
    title: 'Have got/has got để diễn đạt sở hữu',
    objectiveVi: 'Dùng have got và has got để nói ai đó sở hữu hoặc có một đặc điểm.',
    objectiveEn: 'Use have got and has got to express possession or a personal feature.',
    patterns: [
      'I/you/we/they + have got + noun',
      'he/she/it + has got + noun',
      'have/has + subject + got + noun?',
    ],
    uses: ['Express present possession.', 'Describe a feature a person or thing has.'],
    prerequisites: ['SUBJECT_PRONOUNS'],
    rule: 'Use has got with third-person singular subjects and have got with the other subjects.',
    examples: [
      ['AFFIRMATIVE', 'I have got a new phone.', 'Tôi có một chiếc điện thoại mới.'],
      ['NEGATIVE', 'She has not got a car.', 'Cô ấy không có ô tô.'],
      ['QUESTION', 'Have they got any children?', 'Họ có con không?'],
    ],
    error: [
      'He have got a bike.',
      'He has got a bike.',
      'He là ngôi thứ ba số ít nên dùng has got.',
    ],
    exercise: {
      contextVi: 'Bạn kể về gia đình của Nam.',
      sourceVi: 'Nam có một em gái.',
      answers: ['Nam has got a younger sister.', 'Nam has got a little sister.'],
      requirements: ['Use has got for present possession.'],
      vocabulary: [
        'sister',
        'noun',
        'chị hoặc em gái',
        'Một người con gái có cùng cha mẹ.',
        'younger sister — em gái',
      ],
    },
  },
  {
    code: 'PRESENT_SIMPLE_AFFIRMATIVE',
    family: 'PRESENT_SIMPLE',
    cefr: 'A1',
    title: 'Hiện tại đơn: câu khẳng định',
    objectiveVi: 'Dùng hiện tại đơn để nói về thói quen và sự thật, với đuôi -s khi cần.',
    objectiveEn:
      'Use the present simple for routines and facts, including third-person singular agreement.',
    patterns: ['I/you/we/they + base verb', 'he/she/it + verb-s/es'],
    uses: ['Describe routines and repeated actions.', 'State general facts.'],
    prerequisites: ['SUBJECT_PRONOUNS'],
    rule: 'Add -s or -es to the main verb with a third-person singular subject.',
    examples: [
      ['AFFIRMATIVE', 'I walk to work every day.', 'Tôi đi bộ đến chỗ làm mỗi ngày.'],
      ['AFFIRMATIVE', 'Mai studies English at night.', 'Mai học tiếng Anh vào buổi tối.'],
      ['CONTEXTUAL', 'Water boils at 100 degrees Celsius.', 'Nước sôi ở 100 độ C.'],
    ],
    error: [
      'She work on Saturdays.',
      'She works on Saturdays.',
      'Chủ ngữ she cần động từ thêm -s.',
    ],
    exercise: {
      contextVi: 'Bạn mô tả thói quen buổi sáng của bố.',
      sourceVi: 'Bố tôi uống cà phê mỗi sáng.',
      answers: ['My father drinks coffee every morning.', 'My dad drinks coffee every morning.'],
      requirements: ['Use the present simple.', 'Use third-person singular verb agreement.'],
      vocabulary: [
        'coffee',
        'noun',
        'cà phê',
        'Một loại đồ uống thường dùng vào buổi sáng.',
        'drink coffee — uống cà phê',
      ],
    },
  },
  {
    code: 'PRESENT_SIMPLE_NEGATIVE',
    family: 'PRESENT_SIMPLE',
    cefr: 'A1',
    title: 'Hiện tại đơn: câu phủ định',
    objectiveVi: 'Dùng do not và does not để phủ định thói quen hoặc sự thật.',
    objectiveEn: 'Use do not and does not to negate routines or facts.',
    patterns: ['I/you/we/they + do not + base verb', 'he/she/it + does not + base verb'],
    uses: ['Deny a routine.', 'State that a general fact is not true.'],
    prerequisites: ['PRESENT_SIMPLE_AFFIRMATIVE'],
    rule: 'After does not, use the base form of the main verb without -s.',
    examples: [
      ['NEGATIVE', 'I do not eat meat.', 'Tôi không ăn thịt.'],
      ['NEGATIVE', 'He does not drive to work.', 'Anh ấy không lái xe đi làm.'],
      [
        'CONTEXTUAL',
        'This shop does not open on Sundays.',
        'Cửa hàng này không mở cửa vào Chủ nhật.',
      ],
    ],
    error: [
      'She does not likes tea.',
      'She does not like tea.',
      'Sau does not, động từ chính trở về dạng nguyên mẫu.',
    ],
    exercise: {
      contextVi: 'Bạn giải thích thói quen của Linh.',
      sourceVi: 'Linh không xem TV vào buổi tối.',
      answers: ['Linh does not watch TV in the evening.', "Linh doesn't watch TV in the evening."],
      requirements: ['Use does not plus a base verb.'],
      vocabulary: [
        'watch',
        'verb',
        'xem',
        'Hành động nhìn một chương trình trong một khoảng thời gian.',
        'watch TV — xem TV',
      ],
    },
  },
  {
    code: 'PRESENT_SIMPLE_QUESTIONS',
    family: 'PRESENT_SIMPLE',
    cefr: 'A1',
    title: 'Hiện tại đơn: câu hỏi',
    objectiveVi: 'Dùng do hoặc does để hỏi về thói quen và thông tin thường xuyên.',
    objectiveEn: 'Use do or does to ask about routines and regular facts.',
    patterns: [
      'do + I/you/we/they + base verb?',
      'does + he/she/it + base verb?',
      'wh-word + do/does + subject + base verb?',
    ],
    uses: ['Ask about a routine.', 'Request regular or factual information.'],
    prerequisites: ['PRESENT_SIMPLE_NEGATIVE'],
    rule: 'Use does for third-person singular and keep the main verb in its base form.',
    examples: [
      ['QUESTION', 'Do you work on Fridays?', 'Bạn có làm việc vào thứ Sáu không?'],
      ['QUESTION', 'Does Lan live near here?', 'Lan có sống gần đây không?'],
      ['QUESTION', 'Where do they study?', 'Họ học ở đâu?'],
    ],
    error: [
      'Does he plays football?',
      'Does he play football?',
      'Sau does, dùng động từ nguyên mẫu play.',
    ],
    exercise: {
      contextVi: 'Bạn hỏi đồng nghiệp về cách cô ấy đi làm.',
      sourceVi: 'Cô ấy có đi xe buýt đến chỗ làm không?',
      answers: ['Does she take the bus to work?', 'Does she go to work by bus?'],
      requirements: ['Form a present-simple yes/no question with does.'],
      vocabulary: [
        'bus',
        'noun',
        'xe buýt',
        'Phương tiện công cộng chở nhiều hành khách.',
        'take the bus — đi xe buýt',
      ],
    },
  },
  {
    code: 'PAST_SIMPLE_REGULAR',
    family: 'PAST_SIMPLE',
    cefr: 'A2',
    title: 'Quá khứ đơn với động từ có quy tắc',
    objectiveVi: 'Dùng động từ đuôi -ed để kể một hành động đã kết thúc trong quá khứ.',
    objectiveEn: 'Use regular -ed verbs for actions completed at a finished past time.',
    patterns: ['subject + regular verb-ed + complement'],
    uses: ['Describe a completed past action.', 'Tell events in chronological order.'],
    prerequisites: ['PRESENT_SIMPLE_AFFIRMATIVE'],
    rule: 'Use the regular past form when the action belongs to a finished past time.',
    examples: [
      ['AFFIRMATIVE', 'We visited Hue last year.', 'Chúng tôi đã thăm Huế năm ngoái.'],
      ['AFFIRMATIVE', 'She called me yesterday.', 'Cô ấy đã gọi cho tôi hôm qua.'],
      ['CONTEXTUAL', 'The film started at eight.', 'Bộ phim đã bắt đầu lúc tám giờ.'],
    ],
    error: [
      'They visit us yesterday.',
      'They visited us yesterday.',
      'Mốc yesterday yêu cầu dạng quá khứ visited.',
    ],
    exercise: {
      contextVi: 'Bạn kể về cuối tuần vừa rồi.',
      sourceVi: 'Chúng tôi đã dọn dẹp căn hộ vào thứ Bảy.',
      answers: ['We cleaned the apartment on Saturday.', 'We cleaned the flat on Saturday.'],
      requirements: ['Use a regular past-simple verb.', 'Keep the finished time reference.'],
      vocabulary: [
        'apartment',
        'noun',
        'căn hộ',
        'Một nơi ở nằm trong một tòa nhà.',
        'clean the apartment — dọn dẹp căn hộ',
      ],
    },
  },
  {
    code: 'PAST_SIMPLE_IRREGULAR',
    family: 'PAST_SIMPLE',
    cefr: 'A2',
    title: 'Quá khứ đơn với động từ bất quy tắc',
    objectiveVi: 'Dùng dạng quá khứ bất quy tắc để kể hành động đã hoàn tất.',
    objectiveEn: 'Use irregular past forms to describe completed actions.',
    patterns: ['subject + irregular past form + complement'],
    uses: ['Report a completed event.', 'Narrate a sequence in the past.'],
    prerequisites: ['PAST_SIMPLE_REGULAR'],
    rule: 'Use the established irregular past form rather than adding -ed.',
    examples: [
      ['AFFIRMATIVE', 'I went home early.', 'Tôi đã về nhà sớm.'],
      ['AFFIRMATIVE', 'He bought a new laptop.', 'Anh ấy đã mua một chiếc laptop mới.'],
      ['CONTEXTUAL', 'We saw Minh at the station.', 'Chúng tôi đã gặp Minh ở nhà ga.'],
    ],
    error: [
      'She goed to Da Nang.',
      'She went to Da Nang.',
      'Quá khứ của go là went, không phải goed.',
    ],
    exercise: {
      contextVi: 'Bạn kể về bữa tối hôm qua.',
      sourceVi: 'Tôi đã ăn mì với bạn bè.',
      answers: ['I ate noodles with my friends.', 'I ate noodles with friends.'],
      requirements: ['Use the irregular past form ate.'],
      vocabulary: [
        'noodle',
        'noun',
        'mì',
        'Món ăn dạng sợi thường được luộc trong nước.',
        'eat noodles — ăn mì',
      ],
    },
  },
  {
    code: 'PAST_SIMPLE_NEGATIVE',
    family: 'PAST_SIMPLE',
    cefr: 'A2',
    title: 'Quá khứ đơn: câu phủ định',
    objectiveVi: 'Dùng did not cộng động từ nguyên mẫu để phủ định hành động quá khứ.',
    objectiveEn: 'Use did not plus the base verb to negate past actions.',
    patterns: ['subject + did not + base verb + complement'],
    uses: ['Say that a past action did not happen.', 'Correct an assumption about the past.'],
    prerequisites: ['PAST_SIMPLE_IRREGULAR'],
    rule: 'After did not, use the base form of both regular and irregular verbs.',
    examples: [
      ['NEGATIVE', 'I did not sleep well.', 'Tôi đã không ngủ ngon.'],
      ['NEGATIVE', 'They did not arrive on time.', 'Họ đã không đến đúng giờ.'],
      ['CONTEXTUAL', 'Lan did not take the train yesterday.', 'Hôm qua Lan đã không đi tàu.'],
    ],
    error: ['He did not went out.', 'He did not go out.', 'Sau did not, dùng dạng nguyên mẫu go.'],
    exercise: {
      contextVi: 'Bạn đính chính kế hoạch hôm qua.',
      sourceVi: 'Chúng tôi đã không ở nhà tối qua.',
      answers: ['We did not stay at home last night.', "We didn't stay home last night."],
      requirements: ['Use did not plus a base verb.', 'Preserve the past-time phrase.'],
      vocabulary: [
        'stay',
        'verb',
        'ở lại',
        'Tiếp tục ở một nơi thay vì rời đi.',
        'stay at home — ở nhà',
      ],
    },
  },
  {
    code: 'PAST_SIMPLE_QUESTIONS',
    family: 'PAST_SIMPLE',
    cefr: 'A2',
    title: 'Quá khứ đơn: câu hỏi',
    objectiveVi: 'Dùng did để hỏi về hành động đã xảy ra trong quá khứ.',
    objectiveEn: 'Use did to ask about completed past actions.',
    patterns: ['did + subject + base verb?', 'wh-word + did + subject + base verb?'],
    uses: ['Ask whether a past event happened.', 'Ask for details about a past event.'],
    prerequisites: ['PAST_SIMPLE_NEGATIVE'],
    rule: 'After did, use the base form of the main verb.',
    examples: [
      ['QUESTION', 'Did you call Mai?', 'Bạn đã gọi cho Mai chưa?'],
      ['QUESTION', 'Where did they go?', 'Họ đã đi đâu?'],
      ['QUESTION', 'What time did the meeting start?', 'Cuộc họp đã bắt đầu lúc mấy giờ?'],
    ],
    error: [
      'Did she arrived early?',
      'Did she arrive early?',
      'Sau did, dùng động từ nguyên mẫu arrive.',
    ],
    exercise: {
      contextVi: 'Bạn hỏi bạn mình về chuyến đi.',
      sourceVi: 'Bạn đã ở đâu vào cuối tuần trước?',
      answers: ['Where did you stay last weekend?'],
      requirements: ['Use a past-simple wh-question with did.'],
      vocabulary: [
        'weekend',
        'noun',
        'cuối tuần',
        'Khoảng thời gian thứ Bảy và Chủ nhật.',
        'last weekend — cuối tuần trước',
      ],
    },
  },
  {
    code: 'PRESENT_CONTINUOUS_NOW',
    family: 'PRESENT_CONTINUOUS',
    cefr: 'A2',
    title: 'Hiện tại tiếp diễn cho hành động đang diễn ra',
    objectiveVi: 'Dùng be cộng V-ing cho hành động đang diễn ra quanh thời điểm nói.',
    objectiveEn: 'Use be plus an -ing form for an action in progress around now.',
    patterns: ['subject + am/is/are + verb-ing'],
    uses: ['Describe an action happening now.', 'Describe a temporary activity around now.'],
    prerequisites: ['BE_PRESENT_AFFIRMATIVE', 'PRESENT_SIMPLE_AFFIRMATIVE'],
    rule: 'The auxiliary be agrees with the subject and the lexical verb takes -ing.',
    examples: [
      ['AFFIRMATIVE', 'I am reading now.', 'Bây giờ tôi đang đọc sách.'],
      ['NEGATIVE', 'She is not working today.', 'Hôm nay cô ấy không làm việc.'],
      ['QUESTION', 'Are they waiting outside?', 'Họ có đang đợi ở ngoài không?'],
    ],
    error: [
      'He is cook dinner.',
      'He is cooking dinner.',
      'Sau is, động từ hành động cần dạng V-ing.',
    ],
    exercise: {
      contextVi: 'Bạn nói qua điện thoại về việc đang diễn ra.',
      sourceVi: 'Bọn trẻ đang chơi trong vườn.',
      answers: ['The children are playing in the garden.', 'The kids are playing in the garden.'],
      requirements: ['Use present continuous for an action happening now.'],
      vocabulary: [
        'garden',
        'noun',
        'khu vườn',
        'Khoảng đất trồng cây cạnh một ngôi nhà.',
        'in the garden — trong vườn',
      ],
    },
  },
  {
    code: 'PRESENT_SIMPLE_VS_CONTINUOUS',
    family: 'PRESENT_TENSE_CONTRAST',
    cefr: 'A2',
    title: 'Hiện tại đơn và hiện tại tiếp diễn',
    objectiveVi: 'Phân biệt thói quen ổn định với hành động tạm thời hoặc đang diễn ra.',
    objectiveEn: 'Contrast stable routines with temporary or currently unfolding actions.',
    patterns: ['routine: subject + present simple', 'now/temporary: subject + be + verb-ing'],
    uses: [
      'Choose present simple for routines.',
      'Choose present continuous for current temporary actions.',
    ],
    prerequisites: ['PRESENT_SIMPLE_AFFIRMATIVE', 'PRESENT_CONTINUOUS_NOW'],
    rule: 'Choose the tense from the intended time meaning, not from a signal word alone.',
    examples: [
      [
        'CONTRASTIVE',
        'I usually work at home, but today I am working at the office.',
        'Tôi thường làm ở nhà, nhưng hôm nay tôi đang làm ở văn phòng.',
      ],
      ['AFFIRMATIVE', 'Lan takes the bus every day.', 'Lan đi xe buýt mỗi ngày.'],
      ['CONTEXTUAL', 'Please be quiet; the baby is sleeping.', 'Xin hãy yên lặng; em bé đang ngủ.'],
    ],
    error: [
      'I am going to work every day.',
      'I go to work every day.',
      'Every day diễn tả thói quen nên dùng hiện tại đơn.',
    ],
    exercise: {
      contextVi: 'Bạn so sánh thói quen với hôm nay.',
      sourceVi: 'Tôi thường đi bộ, nhưng hôm nay tôi đang đi xe buýt.',
      answers: [
        'I usually walk, but today I am taking the bus.',
        'I usually walk, but I am taking the bus today.',
      ],
      requirements: ['Use present simple for the routine.', 'Use present continuous for today.'],
      vocabulary: [
        'usually',
        'adverb',
        'thường',
        'Trạng từ chỉ điều xảy ra trong phần lớn các lần.',
        'usually walk — thường đi bộ',
      ],
    },
  },
  {
    code: 'COUNTABLE_UNCOUNTABLE_QUANTIFIERS',
    family: 'NOUN_QUANTITY',
    cefr: 'A2',
    title: 'Danh từ đếm được, không đếm được và lượng từ',
    objectiveVi: 'Chọn much, many, a few và a little theo loại danh từ và lượng cần diễn đạt.',
    objectiveEn:
      'Choose much, many, a few, and a little according to noun type and intended quantity.',
    patterns: ['many/a few + plural countable noun', 'much/a little + uncountable noun'],
    uses: ['Ask or talk about quantity.', 'Express a small positive amount.'],
    prerequisites: ['THERE_IS_ARE'],
    rule: 'Use plural forms with countable quantifiers and singular mass nouns with uncountable quantifiers.',
    examples: [
      ['AFFIRMATIVE', 'We have a few chairs.', 'Chúng tôi có một vài chiếc ghế.'],
      ['AFFIRMATIVE', 'There is a little milk left.', 'Còn lại một ít sữa.'],
      ['QUESTION', 'How many tickets do you need?', 'Bạn cần bao nhiêu vé?'],
    ],
    error: [
      'How much books are there?',
      'How many books are there?',
      'Books là danh từ đếm được số nhiều nên dùng many.',
    ],
    exercise: {
      contextVi: 'Bạn kiểm tra đồ ăn trước khi đi mua sắm.',
      sourceVi: 'Chúng ta chỉ còn một ít gạo.',
      answers: ['We only have a little rice left.', 'There is only a little rice left.'],
      requirements: ['Use a little with an uncountable noun.'],
      vocabulary: [
        'rice',
        'noun',
        'gạo hoặc cơm',
        'Một loại lương thực dạng hạt và không đếm trực tiếp.',
        'a little rice — một ít gạo',
      ],
    },
  },
  {
    code: 'COMPARATIVE_ADJECTIVES',
    family: 'COMPARISON',
    cefr: 'A2',
    title: 'So sánh hơn với tính từ',
    objectiveVi: 'So sánh hai người hoặc vật bằng dạng -er hoặc more.',
    objectiveEn: 'Compare two people or things using -er or more.',
    patterns: ['short adjective-er + than', 'more + long adjective + than'],
    uses: ['Compare one quality between two entities.', 'Describe a change in degree.'],
    prerequisites: ['BE_PRESENT_AFFIRMATIVE'],
    rule: 'Choose -er for most short adjectives and more for most longer adjectives.',
    examples: [
      ['AFFIRMATIVE', 'My room is smaller than yours.', 'Phòng của tôi nhỏ hơn phòng của bạn.'],
      ['AFFIRMATIVE', 'This route is more convenient.', 'Tuyến đường này thuận tiện hơn.'],
      ['QUESTION', 'Is the train faster than the bus?', 'Tàu có nhanh hơn xe buýt không?'],
    ],
    error: [
      'This bag is more cheaper.',
      'This bag is cheaper.',
      'Không dùng đồng thời more và đuôi -er.',
    ],
    exercise: {
      contextVi: 'Bạn so sánh hai chiếc điện thoại.',
      sourceVi: 'Chiếc điện thoại này nhẹ hơn chiếc kia.',
      answers: [
        'This phone is lighter than the other one.',
        'This phone is lighter than that one.',
      ],
      requirements: ['Use the comparative form lighter.', 'Make the two compared objects clear.'],
      vocabulary: [
        'light',
        'adjective',
        'nhẹ',
        'Có trọng lượng nhỏ, dễ cầm.',
        'lighter than — nhẹ hơn',
      ],
    },
  },
  {
    code: 'SUPERLATIVE_ADJECTIVES',
    family: 'COMPARISON',
    cefr: 'A2',
    title: 'So sánh nhất với tính từ',
    objectiveVi: 'Dùng dạng so sánh nhất để chọn một người hoặc vật nổi bật trong nhóm.',
    objectiveEn:
      'Use the superlative form to identify one member with the highest degree in a group.',
    patterns: [
      'the + short adjective-est + in/of group',
      'the most + long adjective + in/of group',
    ],
    uses: ['Identify an extreme within a group.', 'Rank people, places, or things.'],
    prerequisites: ['COMPARATIVE_ADJECTIVES'],
    rule: 'A superlative normally uses the and requires an understood comparison group.',
    examples: [
      ['AFFIRMATIVE', 'An is the tallest person in the class.', 'An là người cao nhất lớp.'],
      [
        'AFFIRMATIVE',
        'This is the most useful app on my phone.',
        'Đây là ứng dụng hữu ích nhất trên điện thoại của tôi.',
      ],
      ['QUESTION', 'What is the busiest day of the week?', 'Ngày nào bận nhất trong tuần?'],
    ],
    error: [
      'She is tallest in her family.',
      'She is the tallest in her family.',
      'Dạng so sánh nhất thường cần mạo từ the.',
    ],
    exercise: {
      contextVi: 'Bạn đề xuất một con đường trong ba lựa chọn.',
      sourceVi: 'Đây là con đường ngắn nhất đến nhà ga.',
      answers: [
        'This is the shortest route to the station.',
        'This is the shortest way to the station.',
      ],
      requirements: ['Use the superlative form the shortest.'],
      vocabulary: [
        'route',
        'noun',
        'tuyến đường',
        'Con đường được chọn để đi từ nơi này tới nơi khác.',
        'route to the station — đường đến nhà ga',
      ],
    },
  },
  {
    code: 'FUTURE_GOING_TO_PLANS',
    family: 'FUTURE_EXPRESSIONS',
    cefr: 'A2',
    title: 'Be going to cho dự định tương lai',
    objectiveVi: 'Dùng be going to để nói về dự định đã có trước thời điểm nói.',
    objectiveEn: 'Use be going to for a future intention formed before speaking.',
    patterns: ['subject + am/is/are + going to + base verb'],
    uses: ['Express a prior intention or plan.', 'Ask about another person’s plan.'],
    prerequisites: ['BE_PRESENT_AFFIRMATIVE', 'PRESENT_CONTINUOUS_NOW'],
    rule: 'Use an agreeing form of be before going to and a base verb after to.',
    examples: [
      ['AFFIRMATIVE', 'I am going to learn to cook.', 'Tôi dự định học nấu ăn.'],
      ['NEGATIVE', 'They are not going to move this year.', 'Năm nay họ không định chuyển nhà.'],
      ['QUESTION', 'What are you going to do tonight?', 'Tối nay bạn định làm gì?'],
    ],
    error: [
      'She is going to studies abroad.',
      'She is going to study abroad.',
      'Sau going to dùng động từ nguyên mẫu study.',
    ],
    exercise: {
      contextVi: 'Bạn kể kế hoạch cuối tuần đã được quyết định.',
      sourceVi: 'Chúng tôi định thăm ông bà vào Chủ nhật.',
      answers: ['We are going to visit our grandparents on Sunday.'],
      requirements: ['Use be going to for a prior plan.', 'Use the base verb after going to.'],
      vocabulary: [
        'grandparent',
        'noun',
        'ông hoặc bà',
        'Cha hoặc mẹ của bố hay mẹ bạn.',
        'visit our grandparents — thăm ông bà',
      ],
    },
  },
];
