import type { FoundationCatalogItem as CatalogItem } from './a1-a2.v2';

const make = (
  code: string,
  family: string,
  cefr: 'B1' | 'B2',
  title: string,
  objectiveVi: string,
  objectiveEn: string,
  patterns: string[],
  uses: string[],
  prerequisites: string[],
  rule: string,
  examples: CatalogItem['examples'],
  error: CatalogItem['error'],
  exercise: CatalogItem['exercise'],
): CatalogItem => ({
  code,
  family,
  cefr,
  title,
  objectiveVi,
  objectiveEn,
  patterns,
  uses,
  prerequisites,
  rule,
  examples,
  error,
  exercise,
});

export const intermediateCatalog: CatalogItem[] = [
  make(
    'PRESENT_PERFECT_EXPERIENCE',
    'PRESENT_PERFECT',
    'B1',
    'Hiện tại hoàn thành cho trải nghiệm',
    'Dùng hiện tại hoàn thành để nói về trải nghiệm trước hiện tại mà không nêu thời điểm đã kết thúc.',
    'Use the present perfect for experience before now without a finished past time.',
    ['subject + have/has + past participle', 'have/has + subject + ever + past participle?'],
    ['Describe life experience before now.', 'Ask whether an experience has ever happened.'],
    ['PAST_SIMPLE_IRREGULAR'],
    'Use have or has plus a past participle and do not combine this meaning with a finished past-time expression.',
    [
      ['AFFIRMATIVE', 'I have visited Singapore twice.', 'Tôi đã đến Singapore hai lần.'],
      ['NEGATIVE', 'She has never tried skiing.', 'Cô ấy chưa bao giờ thử trượt tuyết.'],
      ['QUESTION', 'Have you ever met a famous person?', 'Bạn đã từng gặp người nổi tiếng chưa?'],
    ],
    [
      'I have seen him yesterday.',
      'I saw him yesterday.',
      'Yesterday là thời điểm quá khứ đã kết thúc nên dùng quá khứ đơn.',
    ],
    {
      contextVi: 'Bạn chia sẻ trải nghiệm mà không nói thời điểm cụ thể.',
      sourceVi: 'Tôi đã từng đi du lịch một mình.',
      answers: ['I have travelled alone.', 'I have traveled alone.'],
      requirements: [
        'Use the present perfect for life experience.',
        'Do not add a finished past time.',
      ],
      vocabulary: [
        'alone',
        'adverb',
        'một mình',
        'Không có người khác đi cùng.',
        'travel alone — đi du lịch một mình',
      ],
    },
  ),
  make(
    'PRESENT_PERFECT_DURATION',
    'PRESENT_PERFECT',
    'B1',
    'Hiện tại hoàn thành với for và since',
    'Dùng hiện tại hoàn thành với for hoặc since cho trạng thái bắt đầu trước đây và còn tiếp tục.',
    'Use the present perfect with for or since for a state continuing from the past until now.',
    [
      'subject + have/has + past participle + for + duration',
      'subject + have/has + past participle + since + starting point',
    ],
    [
      'Express a continuing state over a duration.',
      'Mark the starting point of a continuing situation.',
    ],
    ['PRESENT_PERFECT_EXPERIENCE'],
    'Use for with a duration and since with a starting point when the situation continues now.',
    [
      ['AFFIRMATIVE', 'We have lived here for six years.', 'Chúng tôi đã sống ở đây được sáu năm.'],
      ['AFFIRMATIVE', 'Lan has known him since 2020.', 'Lan đã biết anh ấy từ năm 2020.'],
      ['QUESTION', 'How long have you worked here?', 'Bạn đã làm ở đây bao lâu rồi?'],
    ],
    [
      'I have lived here since three years.',
      'I have lived here for three years.',
      'Three years là một khoảng thời gian nên dùng for.',
    ],
    {
      contextVi: 'Bạn nói về công việc vẫn đang tiếp tục.',
      sourceVi: 'Tôi đã làm cho công ty này từ năm 2022.',
      answers: [
        'I have worked for this company since 2022.',
        "I've worked for this company since 2022.",
      ],
      requirements: [
        'Use present perfect for a continuing situation.',
        'Use since with the starting year.',
      ],
      vocabulary: [
        'company',
        'noun',
        'công ty',
        'Một tổ chức kinh doanh có nhân viên.',
        'work for a company — làm cho một công ty',
      ],
    },
  ),
  make(
    'PRESENT_PERFECT_VS_PAST_SIMPLE',
    'TENSE_CONTRAST',
    'B1',
    'Hiện tại hoàn thành và quá khứ đơn',
    'Chọn hiện tại hoàn thành cho liên hệ với hiện tại và quá khứ đơn cho thời điểm đã kết thúc.',
    'Choose present perfect for present relevance and past simple for a finished past time.',
    ['unfinished/current relevance: have/has + past participle', 'finished past: past-simple verb'],
    [
      'Contrast unspecified experience with a dated event.',
      'Contrast unfinished and finished time periods.',
    ],
    ['PRESENT_PERFECT_EXPERIENCE', 'PAST_SIMPLE_QUESTIONS'],
    'A finished past-time reference selects past simple; current relevance without such a time may select present perfect.',
    [
      [
        'CONTRASTIVE',
        'I have read that book, but I read it years ago.',
        'Tôi đã đọc quyển đó, nhưng tôi đọc nó từ nhiều năm trước.',
      ],
      [
        'AFFIRMATIVE',
        'She has lost her key, so she cannot get in.',
        'Cô ấy làm mất chìa khóa nên giờ không vào được.',
      ],
      [
        'AFFIRMATIVE',
        'She lost her key yesterday but found it later.',
        'Hôm qua cô ấy làm mất chìa khóa nhưng sau đó đã tìm thấy.',
      ],
    ],
    [
      'Did you ever visit Japan?',
      'Have you ever visited Japan?',
      'Khi hỏi trải nghiệm không có thời điểm kết thúc, dùng hiện tại hoàn thành.',
    ],
    {
      contextVi: 'Bạn nói một sự việc vừa xảy ra và hậu quả còn ở hiện tại.',
      sourceVi: 'Tôi đã làm mất kính nên bây giờ tôi không thể đọc.',
      answers: [
        'I have lost my glasses, so I cannot read now.',
        "I've lost my glasses, so I can't read now.",
      ],
      requirements: [
        'Use present perfect for a current result.',
        'Preserve the present consequence.',
      ],
      vocabulary: [
        'glasses',
        'noun',
        'kính mắt',
        'Vật đeo trước mắt để nhìn rõ hơn.',
        'lose my glasses — làm mất kính',
      ],
    },
  ),
  make(
    'PAST_CONTINUOUS_INTERRUPTED',
    'PAST_CONTINUOUS',
    'B1',
    'Quá khứ tiếp diễn với hành động xen vào',
    'Dùng quá khứ tiếp diễn cho hành động đang diễn ra khi một sự kiện ngắn xen vào.',
    'Use the past continuous for an ongoing background action interrupted by a shorter event.',
    ['subject + was/were + verb-ing + when + past-simple event'],
    ['Set a past background in progress.', 'Show a shorter event interrupting that background.'],
    ['PAST_SIMPLE_IRREGULAR', 'PRESENT_CONTINUOUS_NOW'],
    'Use past continuous for the ongoing background and past simple for the interrupting event.',
    [
      ['CONTEXTUAL', 'I was cooking when the phone rang.', 'Tôi đang nấu ăn thì điện thoại reo.'],
      [
        'CONTEXTUAL',
        'They were walking home when it started to rain.',
        'Họ đang đi bộ về nhà thì trời bắt đầu mưa.',
      ],
      ['QUESTION', 'What were you doing when I called?', 'Bạn đang làm gì khi tôi gọi?'],
    ],
    [
      'I cooked when the phone was ringing.',
      'I was cooking when the phone rang.',
      'Hành động đang diễn ra dùng was cooking; sự kiện xen vào dùng rang.',
    ],
    {
      contextVi: 'Bạn kể một sự cố xảy ra giữa một hoạt động.',
      sourceVi: 'Tôi đang lái xe thì chiếc xe bị hỏng.',
      answers: ['I was driving when the car broke down.'],
      requirements: [
        'Use past continuous for the background action.',
        'Use past simple for the interruption.',
      ],
      vocabulary: [
        'break down',
        'phrasal verb',
        'bị hỏng',
        'Ngừng hoạt động đột ngột, thường nói về máy móc hoặc xe.',
        'the car broke down — chiếc xe bị hỏng',
      ],
    },
  ),
  make(
    'FIRST_CONDITIONAL',
    'CONDITIONALS',
    'B1',
    'Câu điều kiện loại một',
    'Dùng câu điều kiện loại một cho một điều kiện tương lai có khả năng và kết quả của nó.',
    'Use the first conditional for a possible future condition and its likely result.',
    ['if + present simple, will + base verb', 'will + base verb + if + present simple'],
    ['Predict a likely result of a possible condition.', 'State a practical future consequence.'],
    ['FUTURE_GOING_TO_PLANS', 'PRESENT_SIMPLE_AFFIRMATIVE'],
    'Use present simple in the if-clause and will plus a base verb in the result clause.',
    [
      ['AFFIRMATIVE', 'If it rains, we will stay home.', 'Nếu trời mưa, chúng tôi sẽ ở nhà.'],
      [
        'NEGATIVE',
        'You will not improve if you do not practise.',
        'Bạn sẽ không tiến bộ nếu không luyện tập.',
      ],
      [
        'QUESTION',
        'What will you do if the shop is closed?',
        'Bạn sẽ làm gì nếu cửa hàng đóng cửa?',
      ],
    ],
    [
      'If it will rain, we will cancel.',
      'If it rains, we will cancel.',
      'Trong câu điều kiện loại một, mệnh đề if thường dùng hiện tại đơn.',
    ],
    {
      contextVi: 'Bạn nói về khả năng thời tiết ngày mai.',
      sourceVi: 'Nếu ngày mai trời nắng, chúng tôi sẽ đi biển.',
      answers: [
        'If it is sunny tomorrow, we will go to the beach.',
        "If it's sunny tomorrow, we'll go to the beach.",
      ],
      requirements: ['Use present simple in the if-clause.', 'Use will in the result clause.'],
      vocabulary: [
        'beach',
        'noun',
        'bãi biển',
        'Nơi có cát hoặc sỏi cạnh biển.',
        'go to the beach — đi biển',
      ],
    },
  ),
  make(
    'SECOND_CONDITIONAL',
    'CONDITIONALS',
    'B1',
    'Câu điều kiện loại hai',
    'Dùng câu điều kiện loại hai cho tình huống giả định hoặc khó xảy ra ở hiện tại và tương lai.',
    'Use the second conditional for hypothetical or unlikely present and future situations.',
    ['if + past simple, would + base verb'],
    ['Imagine an unreal present situation.', 'Discuss an unlikely future possibility.'],
    ['FIRST_CONDITIONAL'],
    'Use a past form in the if-clause and would plus a base verb in the result clause.',
    [
      [
        'AFFIRMATIVE',
        'If I had more time, I would learn Spanish.',
        'Nếu có thêm thời gian, tôi sẽ học tiếng Tây Ban Nha.',
      ],
      [
        'CONTEXTUAL',
        'She would travel more if flights were cheaper.',
        'Cô ấy sẽ đi du lịch nhiều hơn nếu vé máy bay rẻ hơn.',
      ],
      ['QUESTION', 'What would you do if you found a wallet?', 'Bạn sẽ làm gì nếu nhặt được ví?'],
    ],
    [
      'If I would have time, I would help.',
      'If I had time, I would help.',
      'Không dùng would trong mệnh đề if chuẩn của loại hai.',
    ],
    {
      contextVi: 'Bạn tưởng tượng mình sống gần văn phòng.',
      sourceVi: 'Nếu tôi sống gần hơn, tôi sẽ đi bộ đi làm.',
      answers: ['If I lived closer, I would walk to work.', "If I lived nearer, I'd walk to work."],
      requirements: [
        'Use a past form in the hypothetical if-clause.',
        'Use would plus a base verb for the result.',
      ],
      vocabulary: [
        'closer',
        'adverb',
        'gần hơn',
        'Ở khoảng cách ngắn hơn so với hiện tại.',
        'live closer — sống gần hơn',
      ],
    },
  ),
  make(
    'MODALS_OBLIGATION_ADVICE',
    'MODALITY',
    'B1',
    'Must, have to và should',
    'Phân biệt nghĩa vụ mạnh với lời khuyên bằng must, have to và should.',
    'Distinguish strong obligation from advice using must, have to, and should.',
    [
      'subject + must + base verb',
      'subject + have/has to + base verb',
      'subject + should + base verb',
    ],
    [
      'Express a rule or strong necessity.',
      'Give advice without imposing an absolute requirement.',
    ],
    ['PRESENT_SIMPLE_AFFIRMATIVE'],
    'Use a base verb after a modal; choose should for advice and must or have to for obligation.',
    [
      ['AFFIRMATIVE', 'You must wear a helmet.', 'Bạn phải đội mũ bảo hiểm.'],
      ['AFFIRMATIVE', 'I have to finish this today.', 'Tôi phải hoàn thành việc này hôm nay.'],
      ['AFFIRMATIVE', 'You should get more sleep.', 'Bạn nên ngủ nhiều hơn.'],
    ],
    ['You should to rest.', 'You should rest.', 'Sau should dùng động từ nguyên mẫu không có to.'],
    {
      contextVi: 'Bạn đưa lời khuyên nhẹ nhàng cho một người bạn mệt mỏi.',
      sourceVi: 'Bạn nên nghỉ ngơi tối nay.',
      answers: ['You should rest tonight.', 'You should get some rest tonight.'],
      requirements: ['Use should for advice, not strong obligation.'],
      vocabulary: [
        'rest',
        'verb',
        'nghỉ ngơi',
        'Dừng hoạt động để lấy lại sức.',
        'get some rest — nghỉ ngơi một chút',
      ],
    },
  ),
  make(
    'PASSIVE_PRESENT_PAST',
    'PASSIVE_VOICE',
    'B1',
    'Bị động ở hiện tại đơn và quá khứ đơn',
    'Dùng bị động khi hành động hoặc đối tượng quan trọng hơn người thực hiện.',
    'Use present and past simple passive when the action or affected entity matters more than the agent.',
    ['subject + am/is/are + past participle', 'subject + was/were + past participle'],
    [
      'Describe processes and general facts.',
      'Report a completed action when the agent is secondary or unknown.',
    ],
    ['BE_PRESENT_AFFIRMATIVE', 'PAST_SIMPLE_IRREGULAR'],
    'Use an agreeing form of be plus a past participle and retain the intended tense in be.',
    [
      ['AFFIRMATIVE', 'Coffee is grown in this region.', 'Cà phê được trồng ở vùng này.'],
      ['AFFIRMATIVE', 'The bridge was built in 2010.', 'Cây cầu được xây vào năm 2010.'],
      ['QUESTION', 'When was this photo taken?', 'Bức ảnh này được chụp khi nào?'],
    ],
    [
      'The room cleaned yesterday.',
      'The room was cleaned yesterday.',
      'Câu bị động quá khứ cần was hoặc were trước quá khứ phân từ.',
    ],
    {
      contextVi: 'Bạn mô tả nguồn gốc một sản phẩm.',
      sourceVi: 'Những chiếc túi này được làm tại Việt Nam.',
      answers: ['These bags are made in Vietnam.'],
      requirements: ['Use present simple passive.', 'Make the bags the grammatical subject.'],
      vocabulary: [
        'bag',
        'noun',
        'túi',
        'Đồ dùng để đựng hoặc mang vật khác.',
        'made in Vietnam — được làm tại Việt Nam',
      ],
    },
  ),
  make(
    'RELATIVE_CLAUSES_DEFINING',
    'RELATIVE_CLAUSES',
    'B1',
    'Mệnh đề quan hệ xác định',
    'Dùng who, which hoặc that để xác định rõ người hoặc vật đang được nói đến.',
    'Use who, which, or that to identify the specific person or thing being discussed.',
    ['person + who/that + clause', 'thing + which/that + clause'],
    [
      'Identify a person with essential information.',
      'Identify a thing with essential information.',
    ],
    ['SUBJECT_PRONOUNS'],
    'Do not separate an essential defining relative clause with commas.',
    [
      [
        'AFFIRMATIVE',
        'The woman who lives next door is a doctor.',
        'Người phụ nữ sống bên cạnh là bác sĩ.',
      ],
      [
        'AFFIRMATIVE',
        'I returned the book that you lent me.',
        'Tôi đã trả quyển sách bạn cho mượn.',
      ],
      ['QUESTION', 'Where is the key which opens this door?', 'Chìa khóa mở cửa này ở đâu?'],
    ],
    [
      'The man which called is my uncle.',
      'The man who called is my uncle.',
      'Dùng who thay vì which để chỉ người.',
    ],
    {
      contextVi: 'Bạn xác định một đồng nghiệp cụ thể.',
      sourceVi: 'Người phụ nữ làm việc với tôi đến từ Huế.',
      answers: [
        'The woman who works with me is from Hue.',
        'The woman that works with me comes from Hue.',
      ],
      requirements: ['Use a defining relative clause for a person.', 'Do not insert commas.'],
      vocabulary: [
        'colleague',
        'noun',
        'đồng nghiệp',
        'Người làm việc cùng tổ chức hoặc cùng bạn.',
        'work with me — làm việc cùng tôi',
      ],
    },
  ),
  make(
    'REPORTED_SPEECH_STATEMENTS',
    'REPORTED_SPEECH',
    'B1',
    'Câu tường thuật cho lời nói',
    'Tường thuật lại một phát biểu với thay đổi ngôi và thời gian phù hợp.',
    'Report a statement with appropriate changes to person and time reference.',
    [
      'reporting subject + said (that) + reported clause',
      'reporting subject + told + object + reported clause',
    ],
    ['Report what somebody said.', 'Shift viewpoint when the reporting context requires it.'],
    ['PAST_SIMPLE_REGULAR'],
    'Use tell with an object; use say without a direct personal object and backshift when the reporting viewpoint is past.',
    [
      ['AFFIRMATIVE', 'Mai said that she was tired.', 'Mai nói rằng cô ấy mệt.'],
      [
        'AFFIRMATIVE',
        'He told me that he would call later.',
        'Anh ấy bảo tôi rằng anh ấy sẽ gọi sau.',
      ],
      ['CONTEXTUAL', 'They said they had no questions.', 'Họ nói họ không có câu hỏi nào.'],
    ],
    [
      'She said me that she was busy.',
      'She told me that she was busy.',
      'Khi có tân ngữ me, dùng told thay vì said.',
    ],
    {
      contextVi: 'Bạn thuật lại lời Nam nói hôm qua.',
      sourceVi: 'Nam nói rằng anh ấy đang làm việc ở nhà.',
      answers: ['Nam said that he was working at home.', 'Nam said he was working from home.'],
      requirements: [
        'Use reported speech after a past reporting verb.',
        'Shift the first-person viewpoint to he.',
      ],
      vocabulary: [
        'report',
        'verb',
        'tường thuật',
        'Kể lại điều người khác đã nói hoặc đã xảy ra.',
        'say that — nói rằng',
      ],
    },
  ),
  make(
    'PAST_PERFECT_SEQUENCE',
    'PAST_PERFECT',
    'B2',
    'Quá khứ hoàn thành để sắp xếp sự kiện',
    'Dùng quá khứ hoàn thành để làm rõ sự kiện xảy ra trước một mốc quá khứ khác.',
    'Use the past perfect to make clear which event happened before another past reference point.',
    ['subject + had + past participle + before/by the time + past event'],
    ['Mark an earlier past event.', 'Explain a past result through an earlier cause.'],
    ['PAST_CONTINUOUS_INTERRUPTED', 'PRESENT_PERFECT_VS_PAST_SIMPLE'],
    'Use had plus a past participle for the earlier event when sequence is not otherwise clear.',
    [
      [
        'AFFIRMATIVE',
        'The train had left before we reached the station.',
        'Tàu đã rời đi trước khi chúng tôi đến ga.',
      ],
      [
        'CONTEXTUAL',
        'She was tired because she had not slept well.',
        'Cô ấy mệt vì đã không ngủ ngon.',
      ],
      [
        'QUESTION',
        'Had you met him before the conference?',
        'Bạn đã từng gặp anh ấy trước hội nghị chưa?',
      ],
    ],
    [
      'When I arrived, they already left.',
      'When I arrived, they had already left.',
      'Sự kiện rời đi xảy ra trước mốc arrived nên dùng had left.',
    ],
    {
      contextVi: 'Bạn giải thích vì sao không vào được nhà.',
      sourceVi: 'Tôi nhận ra rằng mình đã để chìa khóa ở văn phòng.',
      answers: [
        'I realised that I had left my keys at the office.',
        'I realized I had left my keys in the office.',
      ],
      requirements: [
        'Use past perfect for the earlier action.',
        'Use past simple for the later realization.',
      ],
      vocabulary: [
        'realise',
        'verb',
        'nhận ra',
        'Bắt đầu hiểu hoặc biết một điều.',
        'realise that — nhận ra rằng',
      ],
    },
  ),
  make(
    'FUTURE_CONTINUOUS',
    'FUTURE_ASPECT',
    'B2',
    'Tương lai tiếp diễn',
    'Dùng tương lai tiếp diễn cho hành động sẽ đang diễn ra tại một thời điểm tương lai.',
    'Use the future continuous for an action that will be in progress at a future time.',
    ['subject + will be + verb-ing'],
    [
      'Describe an action in progress at a future point.',
      'Ask politely about expected future arrangements.',
    ],
    ['PRESENT_CONTINUOUS_NOW', 'FUTURE_GOING_TO_PLANS'],
    'Use will be plus an -ing form and provide a meaningful future reference point.',
    [
      [
        'AFFIRMATIVE',
        'This time tomorrow, I will be flying to Seoul.',
        'Giờ này ngày mai tôi sẽ đang bay đến Seoul.',
      ],
      [
        'NEGATIVE',
        'We will not be using the office next week.',
        'Tuần sau chúng tôi sẽ không sử dụng văn phòng.',
      ],
      ['QUESTION', 'Will you be working late tonight?', 'Tối nay bạn sẽ làm việc muộn chứ?'],
    ],
    ['I will be work at ten.', 'I will be working at ten.', 'Sau will be cần dạng V-ing.'],
    {
      contextVi: 'Bạn mô tả hoạt động tại một giờ cụ thể ngày mai.',
      sourceVi: 'Lúc tám giờ tối mai, tôi sẽ đang học.',
      answers: [
        'At eight tomorrow evening, I will be studying.',
        "At eight tomorrow evening, I'll be studying.",
      ],
      requirements: ['Use future continuous.', 'Keep the specific future reference time.'],
      vocabulary: [
        'study',
        'verb',
        'học',
        'Dành thời gian tìm hiểu hoặc luyện một môn.',
        'at eight tomorrow evening — lúc tám giờ tối mai',
      ],
    },
  ),
  make(
    'FUTURE_PERFECT',
    'FUTURE_ASPECT',
    'B2',
    'Tương lai hoàn thành',
    'Dùng tương lai hoàn thành cho việc sẽ xong trước một hạn hoặc mốc tương lai.',
    'Use the future perfect for something that will be complete before a future deadline or point.',
    ['subject + will have + past participle + by + future time'],
    ['Predict completion by a deadline.', 'Look back from a future reference point.'],
    ['FUTURE_CONTINUOUS', 'PRESENT_PERFECT_EXPERIENCE'],
    'Use will have plus a past participle and make the future completion point clear.',
    [
      [
        'AFFIRMATIVE',
        'By Friday, we will have finished the report.',
        'Đến thứ Sáu, chúng tôi sẽ hoàn thành báo cáo.',
      ],
      [
        'AFFIRMATIVE',
        'She will have worked here for ten years by June.',
        'Đến tháng Sáu, cô ấy sẽ làm ở đây được mười năm.',
      ],
      ['QUESTION', 'Will they have arrived by then?', 'Đến lúc đó họ sẽ đến nơi chưa?'],
    ],
    [
      'I will have finish by noon.',
      'I will have finished by noon.',
      'Sau will have dùng quá khứ phân từ finished.',
    ],
    {
      contextVi: 'Bạn cam kết hoàn thành trước một hạn.',
      sourceVi: 'Đến cuối tuần, tôi sẽ đọc xong quyển sách.',
      answers: [
        'By the end of the week, I will have finished reading the book.',
        "By the end of the week, I'll have finished the book.",
      ],
      requirements: ['Use future perfect.', 'Express completion by the deadline.'],
      vocabulary: [
        'deadline',
        'noun',
        'hạn chót',
        'Thời điểm muộn nhất một việc phải hoàn tất.',
        'by the end of the week — đến cuối tuần',
      ],
    },
  ),
  make(
    'THIRD_CONDITIONAL',
    'CONDITIONALS',
    'B2',
    'Câu điều kiện loại ba',
    'Dùng câu điều kiện loại ba để tưởng tượng kết quả khác cho một quá khứ không thể thay đổi.',
    'Use the third conditional to imagine a different result for an unchangeable past condition.',
    ['if + had + past participle, would have + past participle'],
    ['Express a counterfactual past condition.', 'Reflect on an unreal past result.'],
    ['SECOND_CONDITIONAL', 'PAST_PERFECT_SEQUENCE'],
    'Use past perfect in the if-clause and would have plus a past participle in the result clause.',
    [
      [
        'CONTEXTUAL',
        'If we had left earlier, we would have caught the train.',
        'Nếu rời đi sớm hơn, chúng tôi đã bắt kịp tàu.',
      ],
      [
        'NEGATIVE',
        'She would not have got lost if she had used the map.',
        'Cô ấy đã không bị lạc nếu dùng bản đồ.',
      ],
      [
        'QUESTION',
        'What would you have done if they had refused?',
        'Bạn đã làm gì nếu họ từ chối?',
      ],
    ],
    [
      'If I knew, I would have told you.',
      'If I had known, I would have told you.',
      'Điều kiện quá khứ không có thật cần had known.',
    ],
    {
      contextVi: 'Bạn nhìn lại một cơ hội đã bỏ lỡ.',
      sourceVi: 'Nếu tôi biết về khóa học, tôi đã đăng ký.',
      answers: [
        'If I had known about the course, I would have enrolled.',
        "If I'd known about the course, I would have signed up.",
      ],
      requirements: [
        'Use past perfect in the if-clause.',
        'Use would have plus a past participle in the result.',
      ],
      vocabulary: [
        'enrol',
        'verb',
        'đăng ký tham gia',
        'Chính thức ghi tên vào một khóa học hoặc chương trình.',
        'enrol in a course — đăng ký khóa học',
      ],
    },
  ),
  make(
    'MIXED_CONDITIONAL_PAST_PRESENT',
    'CONDITIONALS',
    'B2',
    'Điều kiện hỗn hợp: nguyên nhân quá khứ, kết quả hiện tại',
    'Liên kết một điều kiện quá khứ không có thật với kết quả trái thực tế ở hiện tại.',
    'Connect an unreal past condition to a counterfactual present result.',
    ['if + had + past participle, would + base verb + now'],
    ['Explain a present state as the unreal result of a past choice.'],
    ['THIRD_CONDITIONAL', 'SECOND_CONDITIONAL'],
    'Use past perfect for the unreal past cause and would plus a base verb for the present result.',
    [
      [
        'CONTEXTUAL',
        'If I had taken that job, I would live in Tokyo now.',
        'Nếu nhận công việc đó, giờ tôi đã sống ở Tokyo.',
      ],
      [
        'CONTEXTUAL',
        'She would be healthier now if she had stopped smoking.',
        'Giờ cô ấy đã khỏe hơn nếu trước đây bỏ thuốc.',
      ],
      [
        'NEGATIVE',
        'If we had checked the route, we would not be lost now.',
        'Nếu đã kiểm tra đường, giờ chúng tôi đã không bị lạc.',
      ],
    ],
    [
      'If I had studied medicine, I would have been a doctor now.',
      'If I had studied medicine, I would be a doctor now.',
      'Kết quả hiện tại dùng would be, không dùng would have been.',
    ],
    {
      contextVi: 'Bạn nói hệ quả hiện tại của một quyết định cũ.',
      sourceVi: 'Nếu tôi đã tiết kiệm nhiều hơn, bây giờ tôi sẽ có đủ tiền.',
      answers: ['If I had saved more, I would have enough money now.'],
      requirements: [
        'Use past perfect for the past condition.',
        'Use would plus a base verb for the present result.',
      ],
      vocabulary: [
        'save',
        'verb',
        'tiết kiệm',
        'Giữ lại tiền thay vì tiêu hết.',
        'save more money — tiết kiệm nhiều tiền hơn',
      ],
    },
  ),
  make(
    'PASSIVE_ADVANCED_FORMS',
    'PASSIVE_VOICE',
    'B2',
    'Bị động với modal và thể hoàn thành',
    'Dùng bị động với modal hoặc perfect để giữ đúng thời gian và sắc thái nghĩa.',
    'Use passive forms with modals or perfect aspect while preserving time and modality.',
    [
      'modal + be + past participle',
      'have/has been + past participle',
      'modal + have been + past participle',
    ],
    [
      'Express modal meaning with an affected subject.',
      'Report a completed action whose agent is secondary.',
    ],
    ['PASSIVE_PRESENT_PAST', 'PRESENT_PERFECT_EXPERIENCE'],
    'Keep the complete auxiliary chain before the past participle.',
    [
      ['AFFIRMATIVE', 'The form must be submitted today.', 'Biểu mẫu phải được nộp hôm nay.'],
      ['AFFIRMATIVE', 'The road has been repaired.', 'Con đường đã được sửa.'],
      ['CONTEXTUAL', 'The error could have been prevented.', 'Lỗi đó lẽ ra có thể được ngăn chặn.'],
    ],
    [
      'The work must completed today.',
      'The work must be completed today.',
      'Bị động sau modal cần be trước quá khứ phân từ.',
    ],
    {
      contextVi: 'Bạn nêu một yêu cầu chính thức.',
      sourceVi: 'Tất cả tài liệu phải được gửi trước thứ Sáu.',
      answers: [
        'All documents must be sent before Friday.',
        'All the documents must be submitted before Friday.',
      ],
      requirements: ['Use a modal passive form.', 'Preserve the deadline.'],
      vocabulary: [
        'document',
        'noun',
        'tài liệu',
        'Văn bản hoặc tệp chứa thông tin.',
        'submit documents — nộp tài liệu',
      ],
    },
  ),
  make(
    'REPORTED_SPEECH_QUESTIONS',
    'REPORTED_SPEECH',
    'B2',
    'Câu hỏi tường thuật',
    'Tường thuật câu hỏi bằng trật tự mệnh đề và liên từ phù hợp.',
    'Report questions using statement word order and an appropriate reporting connector.',
    ['asked + wh-word + subject + verb', 'asked + if/whether + subject + verb'],
    ['Report an information question.', 'Report a yes/no question.'],
    ['REPORTED_SPEECH_STATEMENTS', 'PAST_SIMPLE_QUESTIONS'],
    'Use statement word order after the reporting connector and omit do, does, or did support.',
    [
      ['AFFIRMATIVE', 'She asked where I lived.', 'Cô ấy hỏi tôi sống ở đâu.'],
      [
        'AFFIRMATIVE',
        'He asked whether we were ready.',
        'Anh ấy hỏi liệu chúng tôi đã sẵn sàng chưa.',
      ],
      ['CONTEXTUAL', 'They asked me why I had left early.', 'Họ hỏi vì sao tôi đã rời đi sớm.'],
    ],
    [
      'She asked where did I live.',
      'She asked where I lived.',
      'Câu hỏi tường thuật dùng trật tự chủ ngữ trước động từ.',
    ],
    {
      contextVi: 'Bạn kể lại câu hỏi của quản lý.',
      sourceVi: 'Quản lý hỏi liệu tôi có thể làm việc vào thứ Bảy không.',
      answers: [
        'The manager asked whether I could work on Saturday.',
        'The manager asked if I could work on Saturday.',
      ],
      requirements: [
        'Use if or whether for a reported yes/no question.',
        'Use statement word order.',
      ],
      vocabulary: [
        'manager',
        'noun',
        'người quản lý',
        'Người chịu trách nhiệm điều hành công việc hoặc nhân viên.',
        'the manager asked — quản lý đã hỏi',
      ],
    },
  ),
  make(
    'RELATIVE_CLAUSES_NON_DEFINING',
    'RELATIVE_CLAUSES',
    'B2',
    'Mệnh đề quan hệ không xác định',
    'Thêm thông tin phụ về một danh từ đã xác định bằng mệnh đề có dấu phẩy.',
    'Add non-essential information about an already identified noun using a comma-marked relative clause.',
    ['identified noun, who/which + clause, main clause'],
    [
      'Add optional information about a known person.',
      'Add optional information about a known thing.',
    ],
    ['RELATIVE_CLAUSES_DEFINING'],
    'Set off a non-defining clause with commas and do not replace who or which with that.',
    [
      [
        'AFFIRMATIVE',
        'My brother, who lives in Perth, is visiting us.',
        'Anh trai tôi, người sống ở Perth, đang thăm chúng tôi.',
      ],
      [
        'AFFIRMATIVE',
        'The museum, which opened last year, is free.',
        'Bảo tàng, mở cửa năm ngoái, được vào miễn phí.',
      ],
      [
        'CONTEXTUAL',
        'Mai, whose team won, received an award.',
        'Mai, người có đội chiến thắng, đã nhận giải.',
      ],
    ],
    [
      'Hanoi, that is the capital, is very busy.',
      'Hanoi, which is the capital, is very busy.',
      'Không dùng that trong mệnh đề quan hệ không xác định.',
    ],
    {
      contextVi: 'Bạn thêm thông tin phụ về một người đã xác định.',
      sourceVi: 'Chị Lan, người đã giúp tôi hôm qua, là hàng xóm của tôi.',
      answers: [
        'Lan, who helped me yesterday, is my neighbour.',
        'Ms Lan, who helped me yesterday, is my neighbor.',
      ],
      requirements: ['Use a non-defining relative clause.', 'Set the clause off with commas.'],
      vocabulary: [
        'neighbour',
        'noun',
        'hàng xóm',
        'Người sống gần nhà bạn.',
        'my neighbour — hàng xóm của tôi',
      ],
    },
  ),
  make(
    'MODAL_DEDUCTION_PRESENT_PAST',
    'MODALITY',
    'B2',
    'Modal suy đoán ở hiện tại và quá khứ',
    'Dùng must, might, could và cannot để thể hiện mức chắc chắn khi suy luận.',
    'Use must, might, could, and cannot to express degrees of certainty in present and past deductions.',
    ['present: modal + base verb/be', 'past: modal + have + past participle'],
    [
      'Make a strong or tentative present deduction.',
      'Infer what probably or possibly happened in the past.',
    ],
    ['MODALS_OBLIGATION_ADVICE', 'PRESENT_PERFECT_EXPERIENCE'],
    'Use modal plus have plus a past participle for deductions about a completed past situation.',
    [
      [
        'AFFIRMATIVE',
        'The lights are on, so she must be home.',
        'Đèn đang bật nên chắc cô ấy ở nhà.',
      ],
      ['CONTEXTUAL', 'He might have missed the bus.', 'Có thể anh ấy đã lỡ xe buýt.'],
      ['NEGATIVE', 'They cannot have finished already.', 'Họ không thể nào đã xong rồi.'],
    ],
    [
      'She must went home.',
      'She must have gone home.',
      'Suy đoán về quá khứ cần must have cộng quá khứ phân từ.',
    ],
    {
      contextVi: 'Bạn suy luận từ một dấu hiệu về quá khứ.',
      sourceVi: 'Có lẽ họ đã quên cuộc họp.',
      answers: [
        'They might have forgotten the meeting.',
        'They may have forgotten about the meeting.',
      ],
      requirements: ['Use a past modal deduction.', 'Express possibility rather than certainty.'],
      vocabulary: [
        'forget',
        'verb',
        'quên',
        'Không nhớ một điều cần nhớ hoặc cần làm.',
        'forget the meeting — quên cuộc họp',
      ],
    },
  ),
  make(
    'GERUND_INFINITIVE_MEANING_CHANGE',
    'VERB_COMPLEMENTATION',
    'B2',
    'Gerund và infinitive làm thay đổi nghĩa',
    'Phân biệt các nghĩa khác nhau khi một số động từ đi với V-ing hoặc to-infinitive.',
    'Distinguish changes in meaning when selected verbs take an -ing form or a to-infinitive.',
    [
      'remember/forget + verb-ing: recall a past event',
      'remember/forget + to + verb: remember a required action',
      'stop + verb-ing vs stop + to + verb',
    ],
    [
      'Contrast remembering an event with remembering a task.',
      'Contrast ending an activity with pausing to perform another.',
    ],
    ['PRESENT_CONTINUOUS_NOW'],
    'Select the complement from the intended meaning rather than treating -ing and to-infinitive as interchangeable.',
    [
      [
        'CONTRASTIVE',
        'I remember meeting her, but I forgot to ask her name.',
        'Tôi nhớ đã gặp cô ấy nhưng quên hỏi tên.',
      ],
      ['CONTRASTIVE', 'He stopped smoking last year.', 'Anh ấy đã bỏ hút thuốc năm ngoái.'],
      ['CONTRASTIVE', 'He stopped to answer the phone.', 'Anh ấy dừng lại để nghe điện thoại.'],
    ],
    [
      'Remember locking the door tonight.',
      'Remember to lock the door tonight.',
      'Một việc cần nhớ làm trong tương lai dùng remember to lock.',
    ],
    {
      contextVi: 'Bạn nhắc một việc cần làm sau này.',
      sourceVi: 'Hãy nhớ gửi email trước khi bạn rời đi.',
      answers: ['Remember to send the email before you leave.'],
      requirements: ['Use remember plus a to-infinitive for a future task.'],
      vocabulary: [
        'email',
        'noun',
        'thư điện tử',
        'Tin nhắn được gửi qua hệ thống thư điện tử.',
        'send the email — gửi email',
      ],
    },
  ),
];
